###
POST https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "number": "1234"
}

###
POST https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "1234"
}

###
POST https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "foo",
    "number": "0000"
}

###
POST https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "foo",
    "number": "1234"
}

###
POST https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "bar",
    "number": "1234"
}

###
POST https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "baz",
    "number": "1234"
}

###
GET https://dark-leaf-4555.fly.dev/api/persons HTTP/1.1

### 
DELETE https://dark-leaf-4555.fly.dev/api/persons/577
